service: shoppy-sls

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1

functions:
  hello:
    handler: handler.sendMail
    events:
      - http:
          path: sendmail
          method: get
    request:
      template:
        application/json: '{ "email" : "$input.params(''email'')","fullname" : "$input.params(''fullname'')","totaItems" : "$input.params(''totaItems'')","totalPrice" : "$input.params(''totalPrice'')" }'
